services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: false
    tags:
    - 'controller.service_arguments'

  App\Action\:
    resource: '%kernel.project_dir%/src/Action/'

  App\Action\TelegramWebhookAction:
    arguments:
    - '@request_stack'
    - '@logger'
    - '@serializer'
    - '@App\Service\TelegramReporter'
    - '%env(TELEGRAM_WEBHOOK_SECRET)%'
