services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: false
    tags:
    - { name: console.command }

  App\Command\:
    resource: '%kernel.project_dir%/src/Command/'

  App\Command\SetTelegramWebhook:
    arguments:
    - '@router'
    - '%env(TELEGRAM_WEBHOOK_SECRET)%'
