services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: false
    tags:
    - { name: messenger.message_handler }

  App\MessageHandler\:
    resource: '%kernel.project_dir%/src/MessageHandler/'

  App\MessageHandler\DanbooruPostReporter:
    arguments:
    - '@App\Service\TelegramReporter'
    - '%env(DANBOORU_TELEGRAM_CHAT_ID)%'
