language: 'php'
php:
- '7.2'

cache:
  directories:
  - 'vendor'

env:
  global:
  - DANBOORU_API_KEY=
  - TELEGRAM_BOT_API_KEY=
  - DANBOORU_TELEGRAM_CHAT_ID=
  - APP_ENV=dev
  - APP_SECRET=b09c551d55f9f5d97b9258e8e05a725a
  - DATABASE_HOST=
  - DATABASE_PORT=
  - DATABASE_USER=
  - DATABASE_PASSWORD=
  - DATABASE_DBNAME=

before_install:
# Disable Xdebug
- phpenv config-rm xdebug.ini || return 0

# Install pip
- sudo apt-get -qq install -y python-pip

# Install & setup virtualenv
- pip install --user --upgrade --quiet --disable-pip-version-check virtualenv
- virtualenv venv
- source venv/bin/activate

install:
- composer install --no-progress --no-suggest --no-interaction
- pip install --quiet --disable-pip-version-check --requirement requirements.txt

before_script:
# Disable Xdebug
- phpenv config-rm xdebug.ini || return 0

jobs:
  include:
  - stage: 'Code analysis'
    name: 'Lint code using yamllint'
    script:
    - composer app:lint-yaml

  - stage: 'Code analysis'
    name: 'Lint code using PHP-CS-Fixer'
    script:
    - composer app:lint-php-cs-fixer

  - stage: 'Code analysis'
    name: 'Lint code using CodeSniffer'
    script:
    - composer app:lint-codesniffer

  - stage: 'Code analysis'
    name: 'Analyze code using PHPStan'
    script:
    - bin/console cache:clear
    - composer app:analyze-phpstan
